name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 pylint black

    - name: Run tests
      run: pytest -v

    - name: Run flake8
      run: flake8 .

    - name: Run pylint
      run: pylint app.py test_app.py

    - name: Check formatting with black
      run: black --check .
